Su19_Example/Su19_Example/Models/ErrorViewModel.cs
using System;

namespace Su19_Example.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Su19_Example/Su19_Example/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Su19_Example.Models;

namespace Su19_Example.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Su19_Example/Su19_Example/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Su19_Example.Controllers
{
    public class PeopleController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Bennett()
        {

            return View();
        }

        public IActionResult Arnfield()
        {
            return View();
        }
        public IActionResult Belcher()
        {
            return View();
        }
        public IActionResult Blackman()
        {
            return View();
        }

        public IActionResult Crockett()
        {
            return View();
        }
        public IActionResult Hopkins()
        {
            return View();
        }
        public IActionResult Johnson()
        {
            return View();
        }
        public IActionResult Kelley()
        {
            return View();
        }
        public IActionResult Lawhorn()
        {
            return View();
        }
        public IActionResult Noe()
        {
            return View();
        }
        public IActionResult Sherman()
        {
            return View();
        }

    }
}

Su19_Example/Su19_Example/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<p>This is a website.</p>

Su19_Example/Su19_Example/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    East Tennessee State University<br />
    Box 70711<br />
    Johnson City, TN 37614
</address>

Su19_Example/Su19_Example/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>CSCI 4250-070</h1>
<h2>Software Engineering I</h2>
<h3>Summer 2019</h3>

Su19_Example/Su19_Example/Views/People/Arnfield.cshtml
@{
    ViewData["Title"] = "Arnfield";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Duncan Arnfield, no degree or title</h2>

<p>My concentration is Information Technology, trying to focus on security and forensics. I hope to make enough to have a well-made kitchen, and to make good on effective </p>

Su19_Example/Su19_Example/Views/People/Bennett.cshtml
@{
    ViewData["Title"] = "Bennett";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Brian T. Bennett, Ph.D.</h2>

<p>This is information about Brian Bennett.</p>

Su19_Example/Su19_Example/Views/People/Blackman.cshtml
@{
	ViewData["Title"] = "Blackman";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Daniel P. Blackman</h2>

<p>My concentration is computer science. I want to make lots of money.</p>

Su19_Example/Su19_Example/Views/People/Crockett.cshtml
@{
    ViewData["Title"] = "Bennett";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Caleb J. Crockett</h2>

<p>My concentration is Information Systems with a focus in Accountancy. I would like to pursue analytics, big data, management, or anything else that may peak my intrest.</p>

Su19_Example/Su19_Example/Views/People/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index of People</h2>

<ul>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Arnfield">
            Duncan Arnfield
        </a>
    </li>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Belcher">
            Joseph Belcher
        </a>
    </li>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Bennett">
            Brian Bennett
        </a>
    </li>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Blackman">
            Daniel Blackman
        </a>
    </li>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Crockett">
            Caleb Crockett
        </a>
    </li>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Hopkins">
            Justin Hopkins
        </a>
    </li>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Johnson">
            M. Nicole Johnson
        </a>
    </li>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Kelley">
            Colin Kelley
        </a>
    </li>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Lawhorn">
            Miranda Lawhorn
        </a>
    </li>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Noe">
            Joshua Noe
        </a>
    </li>
    <li>
        <a asp-area="" asp-controller="People" asp-action="Sherman">
            Nicholas Sherman
        </a>
    </li>
</ul>

Su19_Example/Su19_Example/Views/People/Kelley.cshtml
@{
    ViewData["Title"] = "Kelley";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Colin D. Kelley</h2>

<p>My name is Colin Kelley.I am a CS concentration, and I am interested in pursuing a career in Computer Science. I am wanting to eventually be a programmer, and maybe even a software engineer. I have always been interested in programming, and I decided to make a career of it.</p>

Su19_Example/Su19_Example/Views/People/Noe.cshtml
@{
    ViewData["Title"] = "Noe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Joshua W. Noe</h2>

<h3>Concentration</h3>
<p>Information Technology</p>

<h3>Career Interests</h3>
<ul>
    <li>Web Development</li>
</ul>

Su19_Example/Su19_Example/Views/People/Sherman.cshtml
@{
	ViewData["Title"] = "Bennett";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nicholas R. Sherman</h2>

<p>My concentration is computer science. My biggest goal is to eventually work in/with medical technology research teams to develop and create life saving medical software and hardware in the future.</p>

Su19_Example/Su19_Example/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Su19_Example</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Su19_Example</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a></li>
                    <li><a asp-area="" asp-controller="People" asp-action="Index">People</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Su19_Example</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>